# Generated by Django 5.1.4 on 2025-04-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='policy_holder',
        ),
        migrations.AddField(
            model_name='bonus',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='insurance.customer'),
            preserve_default=False,
        ),
    ]
