# Generated by Django 5.1.4 on 2025-04-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_bonus_policy_holder_bonus_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyholder',
            name='payment_mode',
        ),
    ]
